---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-common
  namespace: production-redis-cluster
spec:
  type: NodePort
  clusterIP: 10.109.45.72
  ports:
    - port: 6379
      targetPort: 6379
      name: client
      nodePort: 16380
    - port: 16379
      targetPort: 16379
      name: gossip
      nodePort: 16381
  selector:
    app: redis-cluster-common