---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: k8s-infra
  labels:
    name: prometheus-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "laboratory-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi