apiVersion: v1
kind: Service
metadata:
  name: lamp-api
  namespace: ci-cd-demos
  labels:
    name: lamp-api
spec:
  type: ClusterIP
  clusterIP: 10.106.0.80
  ports:
    - port: 80        # 服务访问端口
      targetPort: 80  # 容器端口
  selector:
    name: lamp-api