---
apiVersion: v1
kind: Service
metadata:
  name: rancher-https
  namespace: cattle-system
  labels:
    name: rancher-https
spec:
  type: NodePort
  clusterIP: 10.101.94.246
  ports:
    - port: 443        # 服务访问端口
      targetPort: 443  # 容器端口
  selector:
    app: rancher