upstream kibana {
    server master.k8s.freedom.org:30049;
    server worker01.k8s.freedom.org:30049;
    server worker02.k8s.freedom.org:30049;
    server worker03.k8s.freedom.org:30049;
}

server {
    listen       80;
    listen       [::]:80;
    server_name  kibana.k8s.freedom.org;
    root         /usr/share/nginx/html;

    access_log  /var/log/nginx/kibana.k8s.freedom.org.access.log  main;
    error_log  /var/log/nginx/kibana.k8s.freedom.org.access.err;

    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass   http://kibana;
    }

    error_page 404 /404.html;
        location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}