apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp-mysql-vars
  namespace: ci-cd-demos
  labels:
    name: lamp-mysql-vars
data:
  MYSQL_ROOT_PASSWORD: "Iam007..."
  MYSQL_DATABASE: "lnmp"
  MYSQL_USER: "Roy"
  MYSQL_PASSWORD: "IamRoy?King:007"