---
- name: download {{ common_pkg }}
  get_url:
    url: "{{ common_pkg_url }}"
    dest: "/tmp/{{ common_pkg }}"
    mode: '0600'

- name: unarchive {{ common_pkg }}
  unarchive:
    src: "/tmp/{{ common_pkg }}"
    dest: /tmp
    keep_newer: yes
    remote_src: yes

- name: load common docker images
  shell: docker load < "{{ item }}"
  with_items: "{{ common_imgs }}"
  args:
    chdir: /tmp