---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: redis
data:
  update_node.sh: |
    #!/bin/bash
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_ID}/" ${REDIS_NODES}
    exec "$@"

  redis.conf: |
    dir /data
    bind 0.0.0.0
    cluster-enabled yes
    cluster-config-file nodes.conf
    logfile redis.log
    cluster-node-timeout 5000
    appendonly yes
    daemonize no
    pidfile redis.pid
    appendfilename appendonly.aof
    protected-mode no