[global]
fsid = 2634d6f4-8277-4417-962d-d91d748b2c1b
mon_initial_members = node01
mon_host = 192.168.2.21
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx

public network = 192.168.2.0/24
cluster network = 192.168.3.0/24

[mon]
mon allow pool delete = true
