apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-api-mysql
  namespace: ci-cd-demos
  labels:
    name: lnmp-api-mysql
data:
  MYSQL_ROOT_PASSWORD: "Iam007..."
  MYSQL_DATABASE: "lnmp"
  MYSQL_USER: "Roy"
  MYSQL_PASSWORD: "IamRoy?King:007"