# Prometheus configuration format https://prometheus.io/docs/prometheus/latest/configuration/configuration/
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: production-prometheus
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: "kube-state-metrics"
      static_configs:
      - targets:
          - kube-state-metrics.production-prometheus:8080
          - kube-state-metrics.production-prometheus:8081

    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: kubernetes-apiservers
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    - job_name: kubernetes-nodes-kubelet
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    - job_name: kubernetes-nodes-cadvisor
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __metrics_path__
        replacement: /metrics/cadvisor
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    - job_name: kubernetes-service-endpoints
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name

    - job_name: kubernetes-services
      kubernetes_sd_configs:
      - role: service
      metrics_path: /probe
      params:
        module:
        - http_2xx
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
      - source_labels:
        - __address__
        target_label: __param_target
      - replacement: blackbox
        target_label: __address__
      - source_labels:
        - __param_target
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name

    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name

    - job_name: 'drill-databases'
      static_configs:
        - targets:
          - mysqld-exporter-account-dbs3-5-m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-account-dbs6-8-m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-account-dbs-1-12-m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-account-dbs6-8-s-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eoms-db1-m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eoms-offline-db1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eoms-offline-db1-s-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db0m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db1m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db2m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db3m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db4m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db5m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db6m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-eshop-db7m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-global-eshop-db-m-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-marketing-db-m1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-member-1-6-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-member7-12-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-mk-activity-db-m1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eoms-db1-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eoms-db1-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eoms-db1-s3-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eoms-db1-s4-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eoms-db1-s5-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db0-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db0-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db1-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db1-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db2-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db2-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db3-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db3-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db4-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db4-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db5-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db5-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db6-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db6-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db7-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-eshop-db7-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-global-eshop-db-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-global-eshop-db-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-member1-6-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-ro-member7-12-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-tc-mix2-db-m1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-tc-mix2-db-s1-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-tc-mix2-db-s2-0.production-prometheus.svc.cluster.local:9104
          - mysqld-exporter-trade-account-dbs1-2-m-0.production-prometheus.svc.cluster.local:9104


    alerting:
      alertmanagers:
      - kubernetes_sd_configs:
          - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: kube-system
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_k8s_app]
          regex: alertmanager
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex:
          action: drop
