---
- name: reload-haproxy
  service: name=haproxy state=reloaded enabled=yes

- name: restart-rsyslog
  service: name=rsyslog state=restarted enabled=yes

- name: systemctl-enable-haproxy
  systemd:
    name: haproxy
    enabled: yes

- name: restart-consul-template
  service:
    name: consul-template
    state: restarted
    enabled: yes
