apiVersion: v1
kind: Secret
metadata:
  name: production-storage-class-rbd-secret
  namespace: production-storage-class-rbd
type: "kubernetes.io/rbd"
data:
  key: QVFBc2xYaGZTVjVHSEJBQWQ4d2g2eHNOSVYrbmtRa1dwK1RURkE9PQ==