kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-ceph-rbd-demo
  namespace: production-storage-class-rbd
spec:
  storageClassName: rbd-provisioner-common
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi