apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: storage-ceph-rbd-public-infra
   namespace: storage-class-ceph
provisioner: ceph.com/rbd-public-infra
parameters:
  monitors: node01.ceph.freedom.org, node02.ceph.freedom.org, node03.ceph.freedom.org
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: storage-class-ceph
  pool: k8s
  userId: admin
  userSecretName: ceph-secret
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
allowVolumeExpansion: true