---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-demo-master
  namespace: production-mysql
data:
  # 初始化zabbix-mysql数据库所需变量。
  MYSQL_ROOT_PASSWORD: "IamPassword000..."
  MYSQL_DATABASE: "demo"
  MYSQL_USER: "demo"
  MYSQL_PASSWORD: "demo"