apiVersion: v1
kind: Service
metadata:
  name: mysql-demo-master
  namespace: production-mysql
  labels:
    name: mysql-demo-master
spec:
  type: NodePort
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
  selector:
    name: mysql-demo-master