[global]
fsid = a11741b4-7b8b-43bf-8f4d-85af6ebc3f0d
mon_initial_members = node01.ceph.freedom.org, node02.ceph.freedom.org, node03.ceph.freedom.org
mon_host = 192.168.2.21, 192.168.2.22, 192.168.2.23
auth_cluster_required = cephx
auth_service_required = cephx
auth_client_required = cephx
public_network = 192.168.2.0/24
cluster_network = 192.168.3.0/24

[mon]
mon allow pool delete = true

