---
- name: install bind and bind-utils packages
  hosts:
    - 192.168.255.254
  user: root
  roles:
    - role: mycat
      vars:
        instances:
          - { instance: drill_customer_account, mycat_server_port: 8066, mycat_manager_port: 9066 } # 当只有一个实例时，不需要配置mycat_server_port和mycat_manager_port。
          - { instance: drill_customer_coupon, mycat_server_port: 8067, mycat_manager_port: 9067 }
          - { instance: drill_customer_member, mycat_server_port: 8068, mycat_manager_port: 9068 }
          - { instance: drill_customer_trade, mycat_server_port: 8069, mycat_manager_port: 9069 }
          - { instance: drill_member_master, member_mycat_pkg: true, mycat_server_port: 8070, mycat_manager_port: 9070 }
          - { instance: drill_member_slave, member_mycat_pkg: true, mycat_server_port: 8071, mycat_manager_port: 9071 }
          - { instance: drill_platform_mkt, mycat_server_port: 8072, mycat_manager_port: 9072 }