---
- name: install consul template
  hosts:
    - 192.168.255.252
  user: root
  roles:
    - role: consul
      vars:
        consul_type: agent
        consul_agent_items:
          services:
            - { name: nginx, port: 8888 }
            - { name: consul-agent, port: 8500 }
            - { name: named, port: 53 }
            - { name: vsftpd, port: 21 }
            - { name: httpd, port: 80 }
            - { name: foreman, port: 8443 }
            - { name: php-fpm, port: 9000 }
            - { name: docker-registry, port: 5000 }

    - role: consul
      vars:
        consul_type: template