---
- name: install consul template
  hosts:
    - 192.168.1.250
  user: root
  roles:
    - role: consul
      vars:
        consul_agent_role: True
        consul_template_role: True
        consul_agent_items:
          services:
            - { name: http, port: 80 }
            - { name: https, port: 443 }
            - { name: consul-agent, port: 8500 }