#sequence stored in datanode
ACTIVITY=member_dbs1
ACTIVITY_COUPON=member_dbs1
ACTIVITY_STORE_CONTROL=member_dbs1
COUPON_TYPE=member_dbs1
COUPON_GOODS_LIMIT=member_dbs1
COUPON_STORE_LIMIT=member_dbs1
FRUITCOIN_GOODS_LIMIT=member_dbs1
FRUITCOIN_STORE_LIMIT=member_dbs1
SMS_TEMPLATE=member_dbs1
SMS_TEMPLATE_PARAM=member_dbs1
MEMBER_TASK_RECORD=member_dbs1
CLIENT_LOG_UPLOAD_TASK=member_dbs1
EMPLOYEE=member_dbs1
ORGANIZATION=member_dbs1
MEMBER_ADDRESS=member_dbs1
MEMBER_TRANSFER=member_dbs1
DYNAMIC_VERIFICATION_CODE=member_dbs1
DYNAMIC_MEMBER_CODE=member_dbs1
MEMBER_LEVEL=member_dbs1
MEMBER_CONSUME=member_dbs1
CONSUME_DETAIL=member_dbs1
MEMBER_CONSUME_JOINACTIVITY=member_dbs1
MEMBER_PAY_INFO=member_dbs1
MEMBER_CONSUME_REFUND=member_dbs1
MEMBER_REFUND_DETAIL=member_dbs1
MEMBER_MODIFY_RECORD=member_dbs1
MEMBER_WALLET_RECORD=member_dbs1
MEMBER_FRUITCOIN_RECORD=member_dbs1
MEMBER_COUPON_RECORD=member_dbs1
MEMBER_INTEGRAL_RECORD=member_dbs1
MEMBER_INVOICE_RECORD=member_dbs1
MEMBER_DEPOSIT_RECORD=member_dbs1
MEMBER_DEDUCTION_RECORD=member_dbs1
MEMBER_DEDUCTION_DETAIL=member_dbs1
ACCOUNT_PRESENT_RECORD =member_dbs1
ACTIVITY_JOIN_RECORD=member_dbs1
MEMBER_SENDMSG_RECORD=member_dbs1
MEMBER_SMS_RECORD=member_dbs1
PUSH_COUPON_RECORD=member_dbs1
PUSH_COUPON_TASK=member_dbs1
TB_AUTO_INCREMENT=member_dbs1
DATA_DICTIONARY=member_dbs1
FEE_JOINT=member_dbs1
DATA_DICTIONARY_TYPE=member_dbs1
DYNAMIC_MEMBER_CODE_RECORD=member_dbs1
WEIXIN_TEMPLATE_MODIFY=member_dbs1
COUPON_STORE_GROUP_LIMIT=member_dbs1
FRUITCOIN_STORE_GROUP_LIMIT=mebmer_dbs1
STORES_NEW_SYNCHRONIZE=member_dbs1
MEMBER_INTEGRAL_LEVEL_DETAIL=member_dbs1
MEMBER_LEVEL_ALTER_RECORD=member_dbs1
MEMBER_UPGRADE_EQUITY_RECORD=member_dbs1
MEMBER_EQUITY=member_dbs1
MEMBER_EQUITY_LEVEL=member_dbs1
MEMBER_LEVEL_LIMIT=member_dbs1
MEMBER_BIRTHDAY_EQUITY_RECORD=member_dbs1
MEMBER_LEVEL_MSG_RULE=member_dbs1
MEMBER_BLACK_WHITE=member_dbs1
MEMBER_FUNCTION_LIMIT=member_dbs1
COMMON_PUSH_COUPON_TASK=member_dbs1
COMMON_PUSH_COUPON_RECORD=member_dbs1
MEMBER_LABEL=member_dbs1
MEMBER_ALIPAY_TEMPLATE=member_dbs1
MONTH_GIFT_PUSH_RECORD=member_dbs1
MEMBER_LEVEL_CHANGE=member_dbs1
MEMBER_INTEGRAL_ORDER=member_dbs1
MEMBER_LEVEL_ADJUST=member_dbs1
STORE_BLACK_WHITE=member_dbs1
MEMBER_ACCOUNT_CHECK=member_dbs1
MEMBER_ACCOUNT_CHECK_DETAIL=member_dbs1
WEIXIN_TEMPLATE_OBJECT_CONFIG=member_dbs1
WEIXIN_TEMPLATE_OBJECT_STORE_LIMIT=member_dbs1
WEIXIN_TEMPLATE_OBJECT_STORE_LIMIT_DETAIL=member_dbs1
WEIXIN_TEMPLATE_OBJECT_STORE_GROUP_LIMIT=member_dbs1
HUNDREDVIP_EXPIRE_PUSH_RECORD=member_dbs1
CONSUME_ACTIVITY=member_dbs1
CONSUME_ACTIVITY_SPECIAL_OFFER_DETAIL=member_dbs1
MEMBER_BINDING_COUPON_RECORD=member_dbs1
TASK_FLAG_RECORD=member_dbs1
RECEIVER_ADDRESS=member_dbs1
HUNDREDVIP_SAVE_MONEY_DETAIL=member_dbs1
HUNDREDVIP_SAVE_MONEY_MONTH=member_dbs1
REFUND_HUNDRED_VIP_RECORD=member_dbs1
MEMBER_MEITUAN=member_dbs1
CONSUME_RELATION_DETAIL=member_dbs1
TEMP_ACTIVITY_JOIN_RECORD=member_dbs1
ELECDEPOSIT_FRUITCOIN_GIFT_CONFIG=member_dbs1
MEMBER_DIANPING_TEMPLATE=member_dbs1
MEMBER_DIANPING=member_dbs1
DEPOSIT_RELATION_DETAIL=member_dbs1
HUNDRED_MODIFY_RELATION_DETAIL=member_dbs1
HUNDREDVIP_SAVE_MONEY_BIGDATA=member_dbs1
HUNDREDVIP_EXPIRED_REFUND_RECORD=member_dbs1
MEMBER_CONSUME_RECEIVE=member_dbs1
MEMBER_DIANPING_ERROR_RECORD=member_dbs1
WX_TEMPLATE_LABEL=member_dbs1
MEMBER_CONSUME_BAK=member_dbs1
CONSUME_DETAIL_BAK=member_dbs1
MEMBER_PAY_INFO_BAK=member_dbs1
MEMBER_CODE_KEY=member_dbs1
BLACKLIST=member_dbs1
SUSPECTED_BLACKLIST=member_dbs1
WHITELIST=member_dbs1
RETURN_VISIT=member_dbs1
BLACKLIST_HISTORY_RECORD=member_dbs1
SUSPECTED_BLACKLIST_HISTORY_RECORD=member_dbs1
WHITELIST_HISTORY_RECORD=member_dbs1
OFFICIAL_ACCOUNT_USER=member_dbs1
OPEN_ACCOUNT_BINDING=member_dbs1
MEMBER_UNION_CARD_ORDER=member_dbs1
THIRD_ORDER=member_dbs1
WX_TEMPLATE_OPERAT_RECORD=member_dbs1
TREE_DATA_DICTIONARY=member_dbs1
MEMBER_AUDIT=member_dbs1

