kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: grafana
  namespace: production-grafana
  labels:
    name: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.7.3
#          resources:
#            requests:
#              memory: "4096M"
#              cpu: "1"
#            limits:
#              memory: "8192M"
#              cpu: "4"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-logs
              mountPath: /var/log/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-client-provisioner-public-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: grafana-logs
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-client-provisioner-public-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi