---
- name: install gor {{ gor_record_ver }} bin
  unarchive:
    src: gor_{{ gor_record_ver }}_x64.tar.gz
    dest: /usr/local/bin

- name: generate gor record service
  template:
    src: gor-record.service.j2
    dest: "{{ systemd_conf_dir }}/gor-record.service"
  notify:
    - systemctl-daemon-reload
    - restart-gor-record