---
- name: mkdir gor record traffic directory
  file:
    path: "{{ gor_traffic_dir }}"
    state: directory
    mode: '0755'

- name: install gor {{ gor_replay_ver }} bin
  unarchive:
    src: gor_{{ gor_replay_ver }}_x64.tar.gz
    dest: /usr/local/bin

- name: generate start and stop gor replay service script
  template:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    mode: "0755"
  with_items:
    - { src: start_gor_replay.sh.j2, dest: start_gor_replay.sh }
    - { src: stop_gor_replay.sh.j2, dest: stop_gor_replay.sh.j2 }

# 因systemd服务不支持%特殊字符，所以弃用。
#- name: generate gor replay service
#  template:
#    src: gor-replay.service.j2
#    dest: "{{ systemd_conf_dir }}/gor-replay.service"
#  notify:
#    - systemctl-daemon-reload
#    - restart-gor-replay