apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-zabbix
  namespace: mysql
  labels:
    name: mysql-zabbix
spec:
  serviceName: mysql-zabbix
  replicas: 1
  selector:
    matchLabels:
      name: mysql-zabbix
  template:
    metadata:
      labels:
        name: mysql-zabbix
    spec:
      containers:
        - name: mysql-zabbix
          image: harbor.freedom.org/docker.io/mysql:5.7.29
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-zabbix-vars
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-zabbix-vars
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-zabbix-vars
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-zabbix-vars
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: mysql-zabbix-data
              mountPath: /var/lib/mysql
            - name: mysql-zabbix-logs
              mountPath: /data
            - name: mysql-zabbix-conf
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: mysql-zabbix-conf
          configMap:
            name: mysql-zabbix-files
  volumeClaimTemplates:
    - metadata:
        name: mysql-zabbix-data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: mysql-zabbix-logs
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-mysql
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi