kind: Deployment
apiVersion: apps/v1
metadata:
  name: cattle-prometheus
  namespace: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cattle-prometheus
  template:
    metadata:
      labels:
        app: cattle-prometheus
    spec:
      serviceAccountName: nfs-client-provisioner-cattle-prometheus
      containers:
        - name: cattle-prometheus-ncp
          image: registry.k8s.example.com:5000/quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs-cattle-prometheus
            - name: NFS_SERVER
              value: 192.168.255.252
            - name: NFS_PATH
              value: /data/k8s_nfs_pvc/cattle-prometheus
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.255.252
            path: /data/k8s_nfs_pvc/cattle-prometheus
