---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-2-conf
  namespace: mysql
data:
  my.cnf: |
    # For advice on how to change settings please see
    # http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html

    [mysqld]
    #
    # Remove leading # and set to the amount of RAM for the most important data
    # cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
    # innodb_buffer_pool_size = 128M
    #
    # Remove leading # to turn on a very important data integrity option: logging
    # changes to the binary log between backups.
    # log_bin
    #
    # Remove leading # to set options mainly useful for reporting servers.
    # The server defaults are faster for transactions and fast SELECTs.
    # Adjust sizes as needed, experiment to find the optimal values.
    # join_buffer_size = 128M
    # sort_buffer_size = 2M
    # read_rnd_buffer_size = 2M
    datadir = /var/lib/mysql
    socket = /var/lib/mysql/mysql.sock

    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links = 0

    log-error = /var/lib/mysql/mysqld.log
    pid-file = /var/lib/mysql/mysqld.pid
    log-bin = /var/lib/mysql/mysql-bin

    # Roy Wong added those lines. 2020-01-09
    # character_set_server = utf8mb4
    # collation_server = utf8mb4_unicode_ci
    character_set_server = utf8

    server_id = 3
    binlog-format = ROW
    expire_logs_days = 15       # 设置binlog过期时间为15天。

    # 使用gtid模式做主从复制。当设置隔离级别为READ-COMMITED必须设置二进制日志格式为ROW
    #添加以下这些选项
    gtid-mode = on                      # 启用gtid类型，否则就是普通的复制架构
    log-slave-updates = true            # slave更新是否记入日志
    lower_case_table_names =1           # 大小写不敏感
    enforce-gtid-consistency = true     # 强制GTID的一致性
    master-info-repository = TABLE      # 主服信息记录库=表/文件
    relay-log-info-repository = TABLE   # 中继日志信息记录库
    sync-master-info = 1                # 同步主库信息
    slave-parallel-workers = 4          # 从服务器的SQL线程数，要复制库数目相同
    binlog-checksum = CRC32             # 校验码
    master-verify-checksum = 1          # 主服校验
    slave-sql-verify-checksum = 1       # 从服校验
    skip_slave_start = 1

    [mysql]
    default_character_set = utf8

    [client]
    default_character_set = utf8