---
drill_customer_account_user: mycat
drill_customer_account_password: mycat
drill_customer_account_write_host_url: "10.8.60.93:{{ mysql_port }}"
drill_customer_account_write_host_user: account_w
drill_customer_account_write_host_password: Efp58ZMNBhdOBPMrpSFbXXIV69zzp3It
drill_customer_account_read_host_url: "10.8.60.93:{{ mysql_port }}"
drill_customer_account_read_host_user: account_w
drill_customer_account_read_host_password: Efp58ZMNBhdOBPMrpSFbXXIV69zzp3It

drill_customer_coupon_user: mycat
drill_customer_coupon_password: mycat
drill_customer_coupon_write_host_url: "10.8.60.20:{{ mysql_port }}"
drill_customer_coupon_write_host_user: coupon_w
drill_customer_coupon_write_host_password: hoayzE157jfPcFZMlnEaw1hzukW9oE62
drill_customer_coupon_read_host_url: "10.8.60.20:{{ mysql_port }}"
drill_customer_coupon_read_host_user: coupon_w
drill_customer_coupon_read_host_password: hoayzE157jfPcFZMlnEaw1hzukW9oE62

drill_customer_member_user: mycat
drill_customer_member_password: mycat
drill_customer_member_write_host_url: "10.8.60.10:{{ mysql_port }}"
drill_customer_member_write_host_user: member_w
drill_customer_member_write_host_password: t0JrghlOoRUue83cDml55oqfkAKvkF9n
drill_customer_member_read_host_url: "10.8.60.132:{{ mysql_port }}"
drill_customer_member_read_host_user: member_r
drill_customer_member_read_host_password: KwgOrJguszqRcJ1Ar1XmdfitEW6NKc7n

# done
drill_customer_trade_user: trade.ms
drill_customer_trade_password: IYfCJ8XUbEJ2oUdOp2o2tVtJsBwrJBLV
drill_customer_trade_write_host_url: "10.8.60.12:{{ mysql_port }}"
drill_customer_trade_write_host_user: trade_w
drill_customer_trade_write_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg
drill_customer_trade_read_host_url: "10.8.60.12:{{ mysql_port }}"
drill_customer_trade_read_host_user: trade_r
drill_customer_trade_read_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg

drill_member_master_user: trade.ms
drill_member_master_password: IYfCJ8XUbEJ2oUdOp2o2tVtJsBwrJBLV
drill_member_master_write_host_url: 10.8.60.12
drill_member_master_write_host_user: trade_w
drill_member_master_write_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg
drill_member_master_read_host_url: 10.8.60.12
drill_member_master_read_host_user: trade_r
drill_member_master_read_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg

drill_member_slave_user: trade.ms
drill_member_slave_password: IYfCJ8XUbEJ2oUdOp2o2tVtJsBwrJBLV
drill_member_slave_write_host_url: 10.8.60.12
drill_member_slave_write_host_user: trade_w
drill_member_slave_write_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg
drill_member_slave_read_host_url: 10.8.60.12
drill_member_slave_read_host_user: trade_r
drill_member_slave_read_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg


drill_platform_mkt_user: trade.ms
drill_platform_mkt_password: IYfCJ8XUbEJ2oUdOp2o2tVtJsBwrJBLV
drill_platform_mkt_write_host_url: 10.8.60.12
drill_platform_mkt_write_host_user: trade_w
drill_platform_mkt_write_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg
drill_platform_mkt_read_host_url: 10.8.60.12
drill_platform_mkt_read_host_user: trade_r
drill_platform_mkt_read_host_password: fSABdBSNEpzEASIh57d8OI2ExuT7wqKg