---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: restart-gor-record
  service:
    name: gor-record
    state: restarted
    enabled: yes

- name: restart-gor-replay
  service:
    name: gor-replay
    state: restarted
    enabled: yes