---
- name: install k8s packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - docker-client-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - docker-common-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - kubeadm-1.16.2-0.x86_64
      - kubectl-1.16.2-0.x86_64
      - kubelet-1.16.2-0.x86_64
      - kubernetes-cni-0.7.5-0.x86_64
  when: is_k8s_host
  notify: restart kubelet