---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone-rbd
  namespace: production-redis-standalone
  labels:
    name: redis-standalone-rbd
spec:
  type: NodePort
  clusterIP: 10.97.72.51
  ports:
    - port: 6379        # 服务访问端口
      targetPort: 6379  # 容器端口
      nodePort: 32653
  selector:
    name: redis-standalone-rbd