---
- name: generate consul template sub hcl
  tags: generate-config
  template:
    src: consul-template/haproxy-hcl.j2
    dest: "{{ consul_template_config_dir }}/haproxy.hcl"
    mode: 0644
  notify: restart-consul-template

- name: generate consul template ctmpl
  tags: generate-consul-template
  template:
    src: consul-template/{{ haproxy_ctmpl }}.j2
    dest: "{{ consul_template_data_dir }}/haproxy.ctmpl"
    variable_start_string: '[['
    variable_end_string: ']]'
    mode: 0644
  notify: restart-consul-template
