---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-zabbix-agent
  namespace: public-infra
data:
  # zabbix-agent端所需变量，此变量应用于运行在DS状态的容器。
  # 此时需要将原POD中运行的zabbix-server端口通过第三方负载均衡代理出来。
  DS_ZBX_SERVER_NAME: "192.168.255.0/24"
  DS_ZBX_SERVER_PORT: "10051"
  DS_ZBX_PASSIVE_ALLOW: "true"
  DS_ZBX_PASSIVESERVERS: "192.168.255.0/24"