apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
  namespace: storage-class
spec:
  storageClassName: rbd-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi