---
- name: generate main config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: master/named.conf.j2, dest: /etc/named.conf }
    - { src: master/named.rfc1912.zones.j2, dest: /etc/named.rfc1912.zones }
  notify: restart bind

- name: generate rfc1912 zone files
  template:
    src:  "master/{{ item }}.zone.j2"
    dest: "{{ bind_zone_dir}}/{{ item }}.zone"
    mode: "0644"
  with_items: "{{ bind_zones }}"
  notify: restart bind