kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-infra
  namespace: storage-class
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns","coredns"]
    verbs: ["list", "get"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-infra
  namespace: storage-class
subjects:
  - kind: ServiceAccount
    name: rbd-infra
    namespace: storage-class
roleRef:
  kind: ClusterRole
  name: rbd-infra
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbd-infra
  namespace: storage-class
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbd-infra
  namespace: storage-class
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbd-infra
subjects:
  - kind: ServiceAccount
    name: rbd-infra
    namespace: storage-class


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbd-infra
  namespace: storage-class
spec:
  selector:
    matchLabels:
      app: rbd-infra
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-infra
    spec:
      containers:
      - name: rbd-infra
        image: harbor.freedom.org/quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd-infra
      serviceAccount: rbd-infra


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbd-infra
  namespace: storage-class