apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
  labels:
    name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-server
  template:
    metadata:
      labels:
        name: zabbix-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: master01.k8s.freedom.org
      containers:
        - name: zabbix-snmptraps
          image: harbor.freedom.org/zabbix/zabbix-snmptraps:centos-4.0.17
        - name: zabbix-java-gateway
          image: harbor.freedom.org/zabbix/zabbix-java-gateway:centos-4.0.17
        - name: zabbix-agent
          image: harbor.freedom.org/zabbix/zabbix-agent:centos-4.0.17
          ports:
            - containerPort: 10050
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_HOST
            - name: ZBX_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_PORT
        - name: zabbix-server
          image: harbor.freedom.org/roy/zabbix/zabbix-server-mysql:latest
          resources:
            requests:
              memory: "256M"
              cpu: 200m
            limits:
              memory: "2048M"
              cpu: 2000m
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ZBX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_NAME
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_HOST
            - name: ZBX_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_PORT
            - name: ZBX_SERVER_LISTENIP
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_LISTENIP
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: DB_SERVER_HOST
            - name: DB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: DB_SERVER_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: MYSQL_PASSWORD
            - name: ZBX_PHP_TZ
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_PHP_TZ
            - name: ZBX_DEBUGLEVEL
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_DEBUGLEVEL
            - name: ZBX_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_TIMEOUT
            - name: ZBX_JAVAGATEWAY_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_JAVAGATEWAY_ENABLE
            - name: ZBX_ENABLE_SNMP_TRAPS
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_ENABLE_SNMP_TRAPS
            - name: ZBX_CACHESIZE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_CACHESIZE
          ports:
            - containerPort: 10051
              hostPort: 10051       # zabbix-server时采用hostPort暴露端口，可以使k8s集群外部主机接入监控。