apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-alertscripts
  namespace: zabbix
  labels:
    name: zabbix-server-alertscripts
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-externalscripts
  namespace: zabbix
  labels:
    name: zabbix-server-externalscripts
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi