---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-redis-standalone
  namespace: public-infra
  labels:
    name: data-redis-standalone
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage-public-infra"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi