---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-standalone
  namespace: public-infra
  labels:
    name: redis-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-standalone
  template:
    metadata:
      labels:
        name: redis-standalone
    spec:
      initContainers:
        - name: sysctl
          image: registry.k8s.example.com:5000/docker.io/busybox:1.31.1
          command: ["sysctl"]
          args: ["-w", "net.core.somaxconn=65535"]
          securityContext:
            privileged: true
        - name: disable-transparent-hugepage
          image: registry.k8s.example.com:5000/docker.io/busybox:1.31.1
          command: ["echo", "never", ">", "/sys/kernel/mm/transparent_hugepage/enabled"]
          securityContext:
            privileged: true
      containers:
        - name: redis-standalone
          image: registry.k8s.example.com:5000/docker.io/redis:5.0.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/redis.conf"] # 配置文件中的daemon值要设置为no。
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /usr/local/etc/redis/
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-redis-standalone
        - name: conf
          configMap:
            name: redis-standalone