apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: production-zabbix
  labels:
    name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-server
  template:
    metadata:
      labels:
        name: zabbix-server
    spec:
      containers:
        - name: zabbix-agent
          image: docker.io/zabbix/zabbix-agent:centos-4.0.17
          ports:
            - containerPort: 10050
          env:
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_HOST
            - name: ZBX_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_PORT
          volumeMounts:
            - name: zabbix-server-zabbix-agentd-d
              mountPath: /etc/zabbix/zabbix_agentd.d
        - name: zabbix-server
          image: docker.io/zabbix/zabbix-server-mysql:centos-4.0.17
          ports:
            - containerPort: 10051
              hostPort: 10051       # zabbix-server时采用hostPort暴露端口，可以使k8s集群外部主机接入监控。
          env:
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_DB_SERVER_HOST
            - name: DB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_DB_SERVER_PORT
            - name: ZBX_LISTENIP
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_SERVER_LISTENIP
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix-server-vars
                  key: ZBX_MYSQL_PASSWORD
          volumeMounts:
            - name: zabbix-server-alertscripts
              mountPath: /usr/lib/zabbix/alertscripts
            - name: zabbix-server-externalscripts
              mountPath: /usr/lib/zabbix/externalscripts
      volumes:
        - name: zabbix-server-zabbix-agentd-d
          persistentVolumeClaim:
            claimName: zabbix-server-zabbix-agentd-d
        - name: zabbix-server-alertscripts
          persistentVolumeClaim:
            claimName: zabbix-server-alertscripts
        - name: zabbix-server-externalscripts
          persistentVolumeClaim:
            claimName: zabbix-server-externalscripts
      nodeSelector:
        kubernetes.io/hostname: worker01.k8s.freedom.org