---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-public-infra-vars
  namespace: mysql
data:
  # 初始化zabbix-mysql数据库所需变量。
  MYSQL_ROOT_PASSWORD: "Iam007..."
  MYSQL_DATABASE: "public"
  MYSQL_USER: "Roy"
  MYSQL_PASSWORD: "IamRoy?King:007"