apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-public-infra
  namespace: mysql
  labels:
    name: mysql-public-infra
spec:
  serviceName: mysql-public-infra
  replicas: 1
  selector:
    matchLabels:
      name: mysql-public-infra
  template:
    metadata:
      labels:
        name: mysql-public-infra
    spec:
      containers:
        - name: mysql
          image: registry.k8s.example.com:5000/docker.io/mysql:5.7.29
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-public-infra-vars
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-public-infra-vars
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-public-infra-vars
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-public-infra-vars
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: logs
              mountPath: /data
            - name: conf
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: conf
          configMap:
            name: mysql-public-infra-files
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: storage-ceph-rbd-public-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: logs
        annotations:
          volume.beta.kubernetes.io/storage-class: storage-ceph-rbd-public-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi