apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-frd-logs
  namespace: ci-cd-demos
  labels:
    name: lamp-frd-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: "laboratory-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi