apiVersion: v1
kind: Service
metadata:
  name: consul-server-gd
  namespace: consul
  labels:
    name: consul-server-gd
spec:
  selector:
    app: consul-server-gd
  type: NodePort
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 30010

    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30011

    - name: rpc
      port: 8400
      targetPort: 8400
      nodePort: 30012

    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
      nodePort: 30013

    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
      nodePort: 30013

    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
      nodePort: 30014

    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
      nodePort: 30014

    - name: server
      port: 8300
      targetPort: 8300
      nodePort: 30015

    - name: consuldns
      port: 8600
      targetPort: 8600
      nodePort: 30016