---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone
  namespace: redis
  labels:
    name: redis-standalone
spec:
  type: NodePort
  clusterIP: 10.97.72.56
  ports:
    - port: 6379        # 服务访问端口
      targetPort: 6379  # 容器端口
  selector:
    name: redis-standalone