apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
    chart: harbor
    heritage: Tiller
    io.cattle.field/appId: harbor
    release: harbor
  name: harbor-harbor-registry-nodeport
  namespace: production-infra
spec:
  selector:
    app: harbor
    component: registry
    release: harbor
  type: NodePort
  clusterIP: 10.99.97.219
  ports:
    - name: registry
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 35811
    - name: controller
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 35812