apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    daemonset: zabbix-agent
  name: zabbix-agent
  namespace: zabbix
spec:
  selector:
    matchLabels:
      daemonset: zabbix-agent
  template:
    metadata:
      labels:
        daemonset: zabbix-agent
    spec:
      containers:
        - name: zabbix-agent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZBX_SERVER_NAME
              value: "zabbix-server.zabbix.svc.cluster.local."
            - name: ZBX_ACTIVESERVERS
              value: "zabbix-server.zabbix.svc.cluster.local."
            - name: ZBX_PASSIVESERVERS
              value: "zabbix-server.zabbix.svc.cluster.local.,192.168.2.0/24"
            - name: ZBX_TIMEOUT
              value: "30"
            - name: ZBX_METADATAITEM
              value: "system.uname"
          image: harbor.freedom.org/roy/zabbix-agent:4.0-centos-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10050 #使用hostport方式暴露地址
              hostPort: 10050
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 50Mi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet