- name: install base packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-accessibility
      - java-1.8.0-openjdk-accessibility-debug
      - java-1.8.0-openjdk-debug
      - java-1.8.0-openjdk-demo
      - java-1.8.0-openjdk-demo-debug
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk-devel-debug
      - java-1.8.0-openjdk-headless
      - java-1.8.0-openjdk-headless-debug
      - java-1.8.0-openjdk-javadoc
      - java-1.8.0-openjdk-javadoc-debug
      - java-1.8.0-openjdk-javadoc-zip
      - java-1.8.0-openjdk-javadoc-zip-debug
      - java-1.8.0-openjdk-src
      - java-1.8.0-openjdk-src-debug