apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertscripts-zabbix-server
  namespace: production-infra
  labels:
    name: alertscripts-zabbix-server
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-client-provisioner-common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: externalscripts-zabbix-server
  namespace: production-infra
  labels:
    name: externalscripts-zabbix-server
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-client-provisioner-common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: include-zabbix-server-agent
  namespace: production-infra
  labels:
    name: include-zabbix-server-agent
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-client-provisioner-common
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi