---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-zabbix-vars
  namespace: mysql-zabbix
data:
  # 初始化zabbix-mysql数据库所需变量。
  MYSQL_ROOT_PASSWORD: "IamPassword000..."
  MYSQL_DATABASE: "zabbix"
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zabbix"