---
- name: install common packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - lrzsz
      - tree
      - nc
      - telnet