---
apiVersion: v1
kind: Service
metadata:
  name: rancher-http
  namespace: cattle-system
  labels:
    name: rancher-http
spec:
  type: NodePort
  clusterIP: 10.101.94.245
  ports:
    - port: 80        # 服务访问端口
      targetPort: 80  # 容器端口
  selector:
    app: rancher