---
- include: common.yml
  tags:
    - common

- include: repos.yml
  tags:
    - repos

- include: rc_local.yml
  tags:
    - rc_local

- include: limits.yml
  tags:
    - limits

- include: pkgs.yml
  tags:
    - pkgs

- include: sysctl.yml
  tags:
    - sysctl