---
- name: delete internel repo file
  file:
    path: /etc/yum.repos.d/*.repo
    state: absent
  ignore_errors: yes

- name: copy common repo files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: repos/base.repo, dest: /etc/yum.repos.d/base.repo }
    - { src: repos/epel.repo, dest: /etc/yum.repos.d/epel.repo }
    - { src: repos/extras.repo, dest: /etc/yum.repos.d/extras.repo }
    - { src: repos/updates.repo, dest: /etc/yum.repos.d/updates.repo }

- name: copy other repo files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: repos/kubernetes.repo, dest: /etc/yum.repos.d/kubernetes.repo }
  when: is_k8s_host