---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: common
  namespace: redis-cluster
spec:
  serviceName: common
  replicas: 6
  selector:
    matchLabels:
      app: common
  template:
    metadata:
      labels:
        app: common
    spec:
      initContainers:
        - name: sysctl
          image: harbor.freedom.org/docker.io/busybox:1.31.1
          command: ["sysctl"]
          args: ["-w", "net.core.somaxconn=65535"]
          securityContext:
            privileged: true
        - name: disable-transparent-hugepage
          image: harbor.freedom.org/docker.io/busybox:1.31.1
          command: ["sh", "-c", "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
      containers:
        - name: common
          image: harbor.freedom.org/docker.io/redis:5.0.7
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          command: ["/conf/update_node.sh", "redis-server", "/conf/redis.conf"]
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: conf
          configMap:
            name: common
            defaultMode: 0755
        - name: host-sys
          hostPath:
            path: /sys
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-redis-cluster
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi