---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-standalone-rbd
  namespace: redis-standalone
  labels:
    name: redis-standalone-rbd
spec:
  serviceName: redis-standalone-rbd
  replicas: 1
  selector:
    matchLabels:
      name: redis-standalone-rbd
  template:
    metadata:
      labels:
        name: redis-standalone-rbd
    spec:
      initContainers:
        - name: sysctl
          image: harbor.freedom.org/docker.io/busybox:1.31.1
          command: ["sysctl"]
          args: ["-w", "net.core.somaxconn=65535"]
          securityContext:
            privileged: true
        - name: disable-transparent-hugepage
          image: harbor.freedom.org/docker.io/busybox:1.31.1
          command: ["sh", "-c", "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
      containers:
        - name: redis-standalone-rbd
          image: harbor.freedom.org/docker.io/redis:5.0.7
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/redis.conf"] # 配置文件中的daemon值要设置为no。
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /usr/local/etc/redis/
              readOnly: true
      volumes:
        - name: conf
          configMap:
            name: redis-standalone-rbd
        - name: host-sys
          hostPath:
            path: /sys
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: rbd-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi